export const policyData = [
    {
        title: 'About YieldVest',
        id: 1,
        content: `
           <p class="pb-2">
           YieldVest is a stock analysis website where you may view an hourly updated list of top stocks to invest in. Our services help investors smartly invest by making use of our impartial and unbiased stock research, fundamental analytical tools, dependable news, and useful market data. For more information about YieldVest, please visit the <a href="/about" class="font-semibold text-[#0B5934]"> About Us</a> page.
           </p> 
           <p class="pb-2">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacyrights and how the law protects You.
           </p>
           <p>
                We use Your Personal data to provide and improve the Service. By using the Service, Youagree to the collection and use of information in accordance with this Privacy Policy.
           </p>
        `
    },
    {
        title: 'Interpretation and Definitions',
        id: 2,
        content: `
            <h3 class="font-semibold pb-2">Interpretation</h3>
            <p class="pb-2">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
            <h3 class="font-semibold pb-2">Definitions</h3>
            <p class=" pb-2">For the purposes of this Privacy Policy:</p>
            <ul class="pl-8">
                <li class="list-disc pb-2">Account means a unique account created for You to access our Service or parts of our Service.</li>
                <li class="list-disc pb-2">Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to My Stock Plug, No, 22 Afolabi Oyawale str.</li>
                <li class="list-disc pb-2">Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li class="list-disc pb-2">Country refers to: Nigeria</li>
                <li class="list-disc pb-2">Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li class="list-disc pb-2">Personal Data is any information that relates to an identified or identifiable individual.</li>
                <li class="list-disc pb-2">Service refers to the Website.</li>
                <li class="list-disc pb-2">Service Provider means any natural or legal person who processes the data onbehalf of the Company. It refers to third-party companies or individuals employedby the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company inanalyzing how the Service is used.</li>
                <li class="list-disc pb-2">Usage Data refers to data collected automatically, either generated by the use of theService or from the Service infrastructure itself (for example, the duration of a pagevisit).</li>
                <li class="list-disc pb-2">Website refers to My Stock Plug, accessible from www.yieldvest.com</li>
                <li class="list-disc pb-2">You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
        `
    },
    {
        title: 'Type of Data Collected',
        id: 3,
        content: `
        <h3 class="font-semibold pb-2">Personal Data</h3>
        <p class=" pb-2">While using Our Service, We may ask You to provide Us with certain personally identifiableinformation that can be used to contact or identify You. Personally identifiable informationmay include, but is not limited to:</p>
        <ul class="pl-8">
            <li class="list-disc pb-2">Email address</li>
            <li class="list-disc pb-2">First name and last name</li>
            <li class="list-disc pb-2">Phone number</li>
            <li class="list-disc pb-2">Address, State, Province, ZIP/Postal code, City</li>
            <li class="list-disc pb-2">Usage Data</li>
        </ul>
        <h3 class="font-semibold pb-2">Usage Data</h3>
        <p class=" pb-2">Usage Data is collected automatically when using the Service.</p>
        <p class=" pb-2">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IPaddress), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p class=" pb-2">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operatingsystem, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
        <p class=" pb-2">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

        <h3 class="font-semibold pb-2">Tracking Technologies and Cookies</h3>
        <p class=" pb-2">We use Cookies and similar tracking technologies to track the activity on Our Service andstore certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies Weuse may include:</p>

        <ul class="pl-8">
            <li class="list-disc pb-2"><span class="font-semibold">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You caninstruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
            <li class="list-disc pb-2"><span class="font-semibold">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visitedthose pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ul>

        <p class=" pb-2">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deletedas soon as You close Your web browser. Learn more about cookies on the Free Privacy Policy website article.</p>

        <p class=" pb-2">We use both Session and Persistent Cookies for the purposes set out below:</p>

        <ul class="pl-8">
            <li class="pb-2 font-semibold">Necessary / Essential Cookies</li>
            <li class="pb-2">Type: Session Cookies</li>
            <li class="pb-2">Administered by: Us</li>
        </ul>

        <p class=" pb-2">Purpose: These Cookies are essential to provide You with services available throughthe Website and to enable You to use some of its features. They help to authenticateusers and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>

        <ul class="pl-8">
            <li class="pb-2 font-semibold">Cookies Policy / Notice Acceptance Cookies</li>
            <li class="pb-2">Type: Persistent Cookies</li>
            <li class="pb-2">Administered by: Us</li>
        </ul>

        <p class=" pb-2">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>

        <ul class="pl-8">
            <li class="pb-2 font-semibold">Functionality Cookies</li>
            <li class="pb-2">Type: Persistent Cookies</li>
            <li class="pb-2">Administered by: Us</li>
        </ul>
        <p class=" pb-2">Purpose: These Cookies allow us to remember choices You make when You use theWebsite, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
        <p class=" pb-2">For more information about the cookies we use and your choices regarding cookies, pleasevisit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
    `
    },
    {
        title: 'Use of Your Personal Data',
        id: 4,
        content: `
            <p class=" pb-2">The Company may use Personal Data for the following purposes:</p>

            <ul class="pl-8">
                <li class="pb-2"><span class="font-semibold">To provide and maintain our Service,</span> including to monitor the usage of our Service.</li>
                <li class="pb-2"><span class="font-semibold">To manage Your Account:</span> to manage Your registration as a user of the Service. ThePersonal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                <li class="pb-2"><span class="font-semibold">For the performance of a contract:</span> the development, compliance and undertakingof the purchase contract for the products, items or services You have purchasedor of any other contract with Us through the Service.</li>
                <li class="pb-2"><span class="font-semibold">To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                <li class="pb-2"><span class="font-semibold">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive suchinformation.</li>
                <li class="pb-2"><span class="font-semibold">To manage Your requests:</span> To attend and manage Your requests to Us.</li>
                <li class="pb-2"><span class="font-semibold">For business transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                <li class="pb-2"><span class="font-semibold">For other purposes:</span> We may use Your information for other purposes, such as dataanalysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketingand your experience.</li>
              
            </ul>

            <p class=" pb-2">We may share Your personal information in the following situations:</p>

            <ul class="pl-8">
                <li class="pb-2"><span class="font-semibold">With Service Providers:</span> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                <li class="pb-2"><span class="font-semibold">For business transfers:</span> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                <li class="pb-2"><span class="font-semibold">For the performance of a contract:</span> the development, compliance and undertakingof the purchase contract for the products, items or services You have purchasedor of any other contract with Us through the Service.</li>
                <li class="pb-2"><span class="font-semibold">With Affiliates:</span> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that Wecontrol or that are under common control with Us.</li>

                <li class="pb-2"><span class="font-semibold">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive suchinformation.</li>
                <li class="pb-2"><span class="font-semibold">With business partners:</span> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>

                <li class="pb-2"><span class="font-semibold">With other users:</span> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may bepublicly distributed outside.</li>

                <li class="pb-2"><span class="font-semibold">With Your consent:</span> We may disclose Your personal information for any other purpose with Your consent.</li>
              
            </ul>
        `
    },
    {
        title: 'Retention of Your Personal Data',
        id: 5,
        content: `
        <p class=" pb-2">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required toretain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p class=" pb-2">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthenthe security or to improve the functionality of Our Service, or We are legally obligated toretain this data for longer time periods.</p>
        `
    },
    {
        title: 'Transfer of Your Personal Data',
        id: 6,
        content: `
        <p class=" pb-2">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on —computers located outside of Your state, province, country or other governmental jurisdiction where the dataprotection laws may differ than those from Your jurisdiction.</p>
        
        <p class=" pb-2">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

        <p class=" pb-2">The Company will take all steps reasonably necessary to ensure that Your data is treatedsecurely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
        `
    },
    {
        title: 'Delete Your Personal Data',
        id: 7,
        content: `
        <p class=" pb-2">You have the right to delete or request that We assist in deleting the Personal Data that Wehave collected about You.</p>
        
        <p class=" pb-2">Our Service may give You the ability to delete certain information about You from within the Service.</p>

        <p class=" pb-2">You may update, amend, or delete your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manageYour personal information. You may also contact Us to request access to, correct, or deleteany personal information that You have provided to Us.</p>

        <p class=" pb-2">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
        `
    },
    {
        title: 'Disclosure of Your Personal Data',
        id: 8,
        content: `
        <h3 class="font-semibold pb-2">Business Transactions</h3>
        <p class=" pb-2">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may betransferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

        <h3 class="font-semibold pb-2">Law enforcement</h3>
        <p class=" pb-2">Under certain circumstances, the Company may be required to disclose Your Personal Dataif required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

        <h3 class="font-semibold pb-2">Other legal requirements</h3>
        <p class=" pb-2">The Company may disclose Your Personal Data in the good faith belief that such actionis necessary to:</p>

        <ul class="pl-8">
            <li class="list-disc pb-2">Comply with a legal obligation</li>
            <li class="list-disc pb-2">Protect and defend the rights or property of the Company</li>
            <li class="list-disc pb-2">Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li class="list-disc pb-2">Protect the personal safety of Users of the Service or the public</li>
            <li class="list-disc pb-2">Protect against legal liability</li>
        </ul>
        `
    },
    {
        title: 'Security of Your Personal Data',
        id: 9,
        content: `
        <p class=" pb-2">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100%secure. While Westrive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        `
    },
    {
        title: 'Children’s Privacy',
        id: 10,
        content: `
        <p class=" pb-2">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data fromanyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>

        <p class=" pb-2">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before Wecollect and use that information.</p>
        `
    },
    {
        title: 'Links to Other Websites',
        id: 11,
        content: `
        <p class=" pb-2">Our Service may contain links to other websites that are not operated by Us. If You click onathird party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>

        <p class=" pb-2">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        `
    },
    {
        title: 'Changes to this Privacy Policy',
        id: 12,
        content: `
        <p class=" pb-2">We may update Our Privacy Policy from time to time. We will notify You of any changes byposting the new Privacy Policy on this page.</p>

        <p class=" pb-2">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>

        <p class=" pb-2">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        `
    },
    {
        title: 'Contact Us',
        id: 13,
        content: `
        <p class=" pb-2">If you have any questions about this Privacy Policy, You can contact us:</p>

        <ul class="pl-8">
            <li class="list-disc pb-2">email: info@yieldvest.com</li>
        </ul>
        `
    }
];
