/* eslint-disable */
export const companyData = [
    {
        "company_id": "GGB",
        "name": "Gerdau S.A.",
        "market_cap": 9186970000,
        "stock_price": 1.17629,
        "dividend_yield": 0.106544,
        "profile_image": "https://financialmodelingprep.com/image-stock/GGB.png",
        "sector": "Basic Materials",
        "category": "Mid Market Cap",
        "ticker_symbol": "GGB",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 9.26529,
            "created_at": "2022-11-24T15:57:01",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Gerdau S.A., together with its subsidiaries, operates as a steel producer company in the Americas. The company operates through Brazil Business, North America Business, South America Business, and Special Steel Business divisions. It provides semi-finished products, including billets, blooms, and slabs; common long rolled products, such as rebars, wire rods, merchant bars, light shapes, and profiles to the construction and manufacturing industries; drawn products comprising barbed and barbless fence wires, galvanized wires, fences, concrete reinforcing wire mesh, nails, and clamps for manufacturing, construction, and agricultural industries; and special steel products used in auto parts, light and heavy vehicles, and agricultural machinery, as well as in the oil and gas, wind energy, machinery and equipment, mining and rail, and other markets. The company also offers flat products, such as hot-rolled steel coils and heavy plates; and resells flat steel products. In addition, it operates three mines that produce iron ore located in the Brazilian state of Minas Gerais. The company sells its products through independent distributors, direct sales from the mills, and its retail network. The company was founded in 1901 and is based in São Paulo, Brazil.",
        "sector": {
            "industry": "Basic Materials",
            "sector_id": "542f5b7b-9c02-4758-8d0d-49e725697e88"
        },
        "stock_price": {
            "stock_price": 1.17629,
            "peg_ratio": 0.00588316,
            "gross_profit_margin": 0.265714,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": 0.106544,
            "annual_stock_return": null,
            "de_ratio": 0.727602,
            "created_at": "2022-11-24T15:56:59",
            "average_volume": null,
            "current_ratio": 2.32535,
            "volume": null,
            "roe_ratio": 0.363675,
            "exchange_platform": null,
            "quick_ratio": 1.0755,
            "company": "GGB",
            "price_risk": null,
            "pb_ratio": 1.17629,
            "stock_price_id": "GGB-2021-12-31",
            "pe_ratio": 3.23444,
            "ps_ratio": 0.639668
        }
    },
    {
        "company_id": "MTH",
        "name": "Meritage Homes Corporation",
        "market_cap": 3136730000,
        "stock_price": 1.23931,
        "dividend_yield": null,
        "profile_image": "https://financialmodelingprep.com/image-stock/MTH.png",
        "sector": "Consumer Cyclical",
        "category": "Mid Market Cap",
        "ticker_symbol": "MTH",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 8.28146,
            "created_at": "2022-11-24T17:57:04",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Meritage Homes Corporation, together with its subsidiaries, designs and builds single-family homes in the United States. The company operates through two segments, Homebuilding and Financial Services. It acquires and develops land; and constructs, markets, and sells homes for first-time and first move-up buyers. The company also offers title insurance and closing/settlement services to its homebuyers. It builds and sells homes in Texas, Arizona, California, Colorado, Florida, North Carolina, South Carolina, Georgia, and Tennessee under the Meritage Homes brand name. Meritage Homes Corporation was founded in 1985 and is based in Scottsdale, Arizona.",
        "sector": {
            "industry": "Consumer Cyclical",
            "sector_id": "c11f4d25-b08f-45e0-9ad4-021c82b1fbc3"
        },
        "category": {
            "category_id": "mid_market_cap_category",
            "name": "Mid Market Cap",
            "market_cap": 2000000000.0
        },
        "ticker": {
            "exchange_symbol": "NYSE",
            "ticker_id": "f9594026-97fa-433c-a96f-3d50e1bf06e9",
            "isin": "US59001A1025",
            "exchange_name": "New York Stock Exchange",
            "symbol": "MTH",
            "exchange_website": null
        },
        "current_ranking": {
            "methodology": "Fundamental Analysis",
            "ranking_id": "74d84d08-7e7f-42c2-b6bd-9542ce0c7aff",
            "updated_at": "2022-11-25T12:14:51",
            "score": 8.28146,
            "company": "MTH",
            "created_at": "2022-11-24T17:57:04"
        },
        "financials": {
            "financial_id": "MTH-2021-12-31",
            "equity": null,
            "earnings_per_share": null,
            "total_revenue": null,
            "operating_cost": null,
            "income_statement_type": "Annual",
            "company": "MTH",
            "date": "2021-12-31",
            "dividend_per_stock": null,
            "growth_rate": 0.14225,
            "ttm": null,
            "income_statement": null,
            "created_at": "2022-11-24T17:57:03"
        },
        "stock_price": {
            "stock_price": 1.23931,
            "peg_ratio": 0.0690442,
            "gross_profit_margin": 0.278849,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": null,
            "annual_stock_return": null,
            "de_ratio": 0.579145,
            "created_at": "2022-11-24T17:57:03",
            "average_volume": null,
            "current_ratio": 8.44765,
            "volume": null,
            "roe_ratio": 0.242231,
            "exchange_platform": null,
            "quick_ratio": 1.41988,
            "company": "MTH",
            "price_risk": null,
            "pb_ratio": 1.23931,
            "stock_price_id": "MTH-2021-12-31",
            "pe_ratio": 5.11623,
            "ps_ratio": 0.732989
        }
    },
    {
        "company_id": "FLNG",
        "name": "FLEX LNG Ltd.",
        "market_cap": 2022220000,
        "stock_price": 1.25057,
        "dividend_yield": 0.0889482,
        "profile_image": "https://financialmodelingprep.com/image-stock/FLNG.png",
        "sector": "Energy",
        "category": "Mid Market Cap",
        "ticker_symbol": "FLNG",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 8.13381,
            "created_at": "2022-11-24T03:23:01",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Flex LNG Ltd., through its subsidiaries, engages in the seaborne transportation of liquefied natural gas (LNG) worldwide. As of February 16, 2022, it owned and operated nine M-type electronically controlled gas injection LNG carriers; and four vessels with generation X dual fuel propulsion systems. It also provides chartering and management services. Flex LNG Ltd. was incorporated in 2006 and is based in Hamilton, Bermuda.",
        "sector": {
            "industry": "Energy",
            "sector_id": "f7497325-f200-44df-b6bd-649a61e3d01e"
        },
        "stock_price": {
            "stock_price": 1.25057,
            "peg_ratio": 0.00355901,
            "gross_profit_margin": 0.608663,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": 0.0889482,
            "annual_stock_return": null,
            "de_ratio": 1.89292,
            "created_at": "2022-11-24T03:21:38",
            "average_volume": null,
            "current_ratio": 1.70907,
            "volume": null,
            "roe_ratio": 0.182378,
            "exchange_platform": null,
            "quick_ratio": 1.63719,
            "company": "FLNG",
            "price_risk": null,
            "pb_ratio": 1.25057,
            "stock_price_id": "FLNG-2021-12-31",
            "pe_ratio": 6.85702,
            "ps_ratio": 3.23846
        }
    },
    {
        "company_id": "DHI",
        "name": "D.R. Horton, Inc.",
        "market_cap": 29096800000,
        "stock_price": 1.45175,
        "dividend_yield": 0.0112399,
        "profile_image": "https://financialmodelingprep.com/image-stock/DHI.png",
        "sector": "Consumer Cyclical",
        "category": "High Market Cap",
        "ticker_symbol": "DHI",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 7.82998,
            "created_at": "2022-11-23T23:21:22",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "D.R. Horton, Inc. operates as a homebuilding company in East, North, Southeast, South Central, Southwest, and Northwest regions in the United States. It engages in the acquisition and development of land; and construction and sale of residential homes in 106 markets across 33 states under the names of D.R. Horton, America's Builder, Express Homes, Emerald Homes, and Freedom Homes. The company constructs and sells single-family detached homes; and attached homes, such as town homes, duplexes, and triplexes. It also provides mortgage financing services; and title insurance policies, and examination and closing services, as well as engages in the residential lot development business. In addition, the company develops, constructs, owns, leases, and sells multi-family and single-family rental properties; owns non-residential real estate, including ranch land and improvements; and owns and operates energy related assets. It primarily serves homebuyers. D.R. Horton, Inc. was founded in 1978 and is headquartered in Arlington, Texas.",
        "sector": {
            "industry": "Consumer Cyclical",
            "sector_id": "c11f4d25-b08f-45e0-9ad4-021c82b1fbc3"
        },
        "stock_price": {
            "stock_price": 1.45175,
            "peg_ratio": 0.119253,
            "gross_profit_margin": 0.313743,
            "date": "2022-09-30",
            "total_price_value": null,
            "dividend_yield": 0.0112399,
            "annual_stock_return": null,
            "de_ratio": 0.544717,
            "created_at": "2022-11-23T23:21:22",
            "average_volume": null,
            "current_ratio": 3.25778,
            "volume": null,
            "roe_ratio": 0.301991,
            "exchange_platform": null,
            "quick_ratio": 0.342054,
            "company": "DHI",
            "price_risk": null,
            "pb_ratio": 1.45175,
            "stock_price_id": "DHI-2022-09-30",
            "pe_ratio": 4.80727,
            "ps_ratio": 0.841057
        }
    },
    {
        "company_id": "RH",
        "name": "RH",
        "market_cap": 6558970000,
        "stock_price": 7.30421,
        "dividend_yield": null,
        "profile_image": "https://financialmodelingprep.com/image-stock/RH.png",
        "sector": "Consumer Cyclical",
        "category": "Mid Market Cap",
        "ticker_symbol": "RH",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 6.95449,
            "created_at": "2022-11-24T10:16:14",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "RH, together with its subsidiaries, operates as a retailer in the home furnishings. It offers products in various categories, including furniture, lighting, textiles, bathware, décor, outdoor and garden, and child and teen furnishings. The company provides its products through its retail galleries; and Source Books, a series of catalogs, as well as online through rh.com, rhbabyandchild.com, rhteen.com, and rhmodern.com, as well as waterworks.com. As of January 29, 2022, it operated a total of 67 RH Galleries and 38 RH outlet stores in 30 states in the District of Columbia and Canada, as well as 14 Waterworks showrooms throughout the United States and the United Kingdom. The company was formerly known as Restoration Hardware Holdings, Inc. and changed its name to RH in January 2017. RH was incorporated in 2011 and is headquartered in Corte Madera, California.",
        "sector": {
            "industry": "Consumer Cyclical",
            "sector_id": "c11f4d25-b08f-45e0-9ad4-021c82b1fbc3"
        },
        "stock_price": {
            "stock_price": 7.30421,
            "peg_ratio": 0.0809667,
            "gross_profit_margin": 0.493615,
            "date": "2022-01-29",
            "total_price_value": null,
            "dividend_yield": null,
            "annual_stock_return": null,
            "de_ratio": 3.73432,
            "created_at": "2022-11-24T10:16:14",
            "average_volume": null,
            "current_ratio": 2.90615,
            "volume": null,
            "roe_ratio": 0.588362,
            "exchange_platform": null,
            "quick_ratio": 2.12413,
            "company": "RH",
            "price_risk": null,
            "pb_ratio": 7.30421,
            "stock_price_id": "RH-2022-01-29",
            "pe_ratio": 12.4145,
            "ps_ratio": 2.27411
        }
    },
    {
        "company_id": "TEX",
        "name": "Terex Corporation",
        "market_cap": 3055050000,
        "stock_price": 2.58177,
        "dividend_yield": 0.0116939,
        "profile_image": "https://financialmodelingprep.com/image-stock/TEX.png",
        "sector": "Industrials",
        "category": "Mid Market Cap",
        "ticker_symbol": "TEX",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 6.81965,
            "created_at": "2022-11-24T11:16:16",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Terex Corporation manufactures and sells aerial work platforms and materials processing machinery worldwide. It operates in two segments, Aerial Work Platforms (AWP) and Materials Processing (MP). The AWP segment designs, manufactures, services, and markets aerial work platform equipment, utility equipment, and telehandlers under the Terex and Genie brands. Its products include portable material lifts, portable aerial work platforms, trailer-mounted articulating booms, self-propelled articulating and telescopic booms, scissor lifts, utility equipment, and telehandlers, as well as related components and replacement parts for construction and maintenance of industrial, commercial, institutional, and residential buildings and facilities, utility and telecommunication lines, construction and foundation drilling applications, and other commercial operations, as well as in tree trimming and various infrastructure projects. The MP segment's materials processing and specialty equipment includes crushers, washing systems, screens, trommels, apron feeders, material handlers, pick and carry cranes, rough terrain cranes, tower cranes, wood processing, biomass and recycling equipment, concrete mixer trucks and concrete pavers, conveyors, and related components and replacement parts under the Terex, Powerscreen, Fuchs, EvoQuip, Canica, Cedarapids, CBI, Simplicity, Franna, Terex Ecotec, Finlay, Terex Washing Systems, Terex MPS, Terex Jaques, Terex Advance, ProStack, Terex Bid-Well, MDS, and Terex Recycling Systems brands and business lines. Its products are used in construction, infrastructure, and recycling projects; quarrying and mining, and material handling applications; maintenance applications to lift equipment or material; and landscaping and biomass production industries. The company offers financing solutions to assist customers in the rental, leasing, and acquisition of its products. Terex Corporation was incorporated in 1986 and is based in Norwalk, Connecticut.",
        "sector": {
            "industry": "Industrials",
            "sector_id": "881b827b-e7bc-4819-8403-c18410a67cea"
        },
        "stock_price": {
            "stock_price": 2.58177,
            "peg_ratio": 0.00585925,
            "gross_profit_margin": 0.194865,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": 0.0116939,
            "annual_stock_return": null,
            "de_ratio": 1.58066,
            "created_at": "2022-11-24T11:16:15",
            "average_volume": null,
            "current_ratio": 1.94285,
            "volume": null,
            "roe_ratio": 0.199081,
            "exchange_platform": null,
            "quick_ratio": 0.851302,
            "company": "TEX",
            "price_risk": null,
            "pb_ratio": 2.58177,
            "stock_price_id": "TEX-2021-12-31",
            "pe_ratio": 12.9685,
            "ps_ratio": 0.737042
        }
    },
    {
        "company_id": "JLL",
        "name": "Jones Lang LaSalle Incorporated",
        "market_cap": 7713620000,
        "stock_price": 1.99683,
        "dividend_yield": null,
        "profile_image": "https://financialmodelingprep.com/image-stock/JLL.png",
        "sector": "Real Estate",
        "category": "Mid Market Cap",
        "ticker_symbol": "JLL",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 6.66001,
            "created_at": "2022-11-24T00:21:24",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Jones Lang LaSalle Incorporated, a professional services company, provides real estate and investment management services in Americas, Europe, the Middle East, Africa, and the Asia Pacific. The company offers a range of real estate services, including agency leasing and tenant representation services; and capital market services, such as debt advisory, loan sales, equity advisory, loan servicing, merger and acquisition, corporate advisory, and investment sales and advisory services. It also provides on-site management services for office, industrial, retail, multifamily residential, and specialty properties; integrated facilities management services; designing, building, management, and consulting services to tenants of leased space, owners in self-occupied buildings, and owners of real estate investments; and advisory, consulting, valuation, and energy and sustainability services. In addition, the company offers investment management services to institutional and retail investors, including high-net-worth individuals. It provides its services to real estate owners, occupiers, investors, and developers for various property types, including cultural, educational, government, healthcare, laboratory, hotel, hospitality, and sports facilities; industrial and warehouse, office, and residential properties; retail and shopping malls; critical environment, data, transportation, and sort and fulfillment centers; infrastructure projects; and military housings. The company was formerly known as LaSalle Partners Incorporated and changed its name to Jones Lang LaSalle Incorporated in March 1999. Jones Lang LaSalle Incorporated was incorporated in 1997 and is headquartered in Chicago, Illinois.",
        "sector": {
            "industry": "Real Estate",
            "sector_id": "34774b54-bb73-4fff-bcc3-84d29b3a2f78"
        },
        "stock_price": {
            "stock_price": 1.99683,
            "peg_ratio": 0.0903873,
            "gross_profit_margin": 0.570331,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": null,
            "annual_stock_return": null,
            "de_ratio": 1.46997,
            "created_at": "2022-11-24T00:21:23",
            "average_volume": null,
            "current_ratio": 0.984768,
            "volume": null,
            "roe_ratio": 0.155475,
            "exchange_platform": null,
            "quick_ratio": 0.907577,
            "company": "JLL",
            "price_risk": null,
            "pb_ratio": 1.99683,
            "stock_price_id": "JLL-2021-12-31",
            "pe_ratio": 12.8434,
            "ps_ratio": 0.637692
        }
    },
    {
        "company_id": "KT",
        "name": "KT Corporation",
        "market_cap": 7097500000,
        "stock_price": 0.455346,
        "dividend_yield": 0.0513723,
        "profile_image": "https://financialmodelingprep.com/image-stock/KT.png",
        "sector": "Communication Services",
        "category": "Mid Market Cap",
        "ticker_symbol": "KT",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 6.51181,
            "created_at": "2022-11-24T11:16:16",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "KT Corporation provides integrated telecommunications and platform services in Korea and internationally. The company offers fixed-line telephone services, including local, domestic long-distance, international long-distance, and voice over Internet protocol telephone services, as well as interconnection services; broadband Internet access service and other Internet-related services; and data communication services, such as fixed-line and leased line services, as well as broadband Internet connection services. It also provides media and content services, including IPTV, satellite TV, digital music, e-commerce, online advertising consulting, and digital comics and novels services; and credit card processing and other financial services. In addition, the company offers information technology and network services, and satellite services; sells handsets and miscellaneous telecommunications equipment; develops and sells residential units and commercial real estate; and rents real estate properties. Further, it maintains public telephones; offers security, B2C and B2B, investment fund, software development and data processing, value added network, system integration and maintenance, mobile marketing, PCS distribution, satellite broadcasting, cloud system implementation, network installation and management, and data center development and related services. Additionally, the company is involved in the Internet banking ASP and security solutions, residential building development and supply, sports group management, technology business finance, software development and supply, submarine cable construction and maintenance, and trunk radio systems businesses. As of December 31, 2020, the company served approximately 22.3 million mobile subscribers and 8.8 million IPTV subscribers. The company was formerly known as Korea Telecom Corp. and changed its name to KT Corporation in March 2002. KT Corporation was founded in 1981 and is headquartered in Seongnam, South Korea.",
        "sector": {
            "industry": "Communication Services",
            "sector_id": "cd172021-651b-4c69-b710-3dfa04068f76"
        },
        "stock_price": {
            "stock_price": 0.455346,
            "peg_ratio": 0.0438682,
            "gross_profit_margin": 0.596804,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": 0.0513723,
            "annual_stock_return": null,
            "de_ratio": 1.37496,
            "created_at": "2022-11-24T11:16:16",
            "average_volume": null,
            "current_ratio": 1.17731,
            "volume": null,
            "roe_ratio": 0.0906003,
            "exchange_platform": null,
            "quick_ratio": 0.923183,
            "company": "KT",
            "price_risk": null,
            "pb_ratio": 0.455346,
            "stock_price_id": "KT-2021-12-31",
            "pe_ratio": 5.02588,
            "ps_ratio": 0.273898
        }
    },
    {
        "company_id": "EMR",
        "name": "Emerson Electric Co.",
        "market_cap": 56709300000,
        "stock_price": 3.17599,
        "dividend_yield": 0.0236012,
        "profile_image": "https://financialmodelingprep.com/image-stock/EMR.png",
        "sector": "Industrials",
        "category": "High Market Cap",
        "ticker_symbol": "EMR",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 6.45067,
            "created_at": "2022-11-24T15:57:01",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Emerson Electric Co., a technology and engineering company, provides various solutions for customers in industrial, commercial, and consumer markets in the Americas, Asia, the Middle East, Africa, and Europe. The company operates through Automation Solutions, AspenTech, and Commercial & Residential Solutions segments. The Automation Solutions segment offers measurement and analytical instrumentation, industrial valves and equipment, and process control software and systems. It serves oil and gas, refining, chemicals, power generation, life sciences, food and beverage, automotive, pulp and paper, metals and mining, and municipal water supplies markets. The AspenTech segment provides asset optimization software that enables industrial manufacturers to design, operate, and maintain their operations for enhancing performance through a combination of decades of modeling, simulation, and optimization capabilities. The Commercial & Residential Solutions segment offers residential and commercial heating and air conditioning products, such as reciprocating and scroll compressors; system protector and flow control devices; standard, programmable, and Wi-Fi thermostats; monitoring equipment and electronic controls for gas and electric heating systems; gas valves for furnaces and water heaters; ignition systems for furnaces; and temperature sensors and controls. It also provides reciprocating, scroll, and screw compressors; precision flow controls; system diagnostics and controls; and environmental control systems. In addition, this segment offers air conditioning, refrigeration, and lighting control technologies, as well as facility design and product management, site commissioning, facility monitoring, and energy modeling services; and tools for professionals and homeowners. The company was incorporated in 1890 and is headquartered in Saint Louis, Missouri.",
        "sector": {
            "industry": "Industrials",
            "sector_id": "881b827b-e7bc-4819-8403-c18410a67cea"
        },
        "stock_price": {
            "stock_price": 3.17599,
            "peg_ratio": 0.391347,
            "gross_profit_margin": 0.417138,
            "date": "2022-09-30",
            "total_price_value": null,
            "dividend_yield": 0.0236012,
            "annual_stock_return": null,
            "de_ratio": 0.364795,
            "created_at": "2022-11-24T13:22:43",
            "average_volume": null,
            "current_ratio": 1.09374,
            "volume": null,
            "roe_ratio": 0.197965,
            "exchange_platform": null,
            "quick_ratio": 0.618748,
            "company": "EMR",
            "price_risk": null,
            "pb_ratio": 3.17599,
            "stock_price_id": "EMR-2022-09-30",
            "pe_ratio": 16.0432,
            "ps_ratio": 2.63994
        }
    },
    {
        "company_id": "BEPC",
        "name": "Brookfield Renewable Corporation",
        "market_cap": 5538530000,
        "stock_price": 1.56826,
        "dividend_yield": null,
        "profile_image": "https://financialmodelingprep.com/image-stock/BEPC.png",
        "sector": "Utilities",
        "category": "Mid Market Cap",
        "ticker_symbol": "BEPC",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 6.01822,
            "created_at": "2022-11-23T23:21:22",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Brookfield Renewable Corporation owns and operates a portfolio of renewable energy power generating facilities primarily in the United States, Europe, Colombia, and Brazil. It operates hydroelectric, wind, and solar power plants with an installed capacity of approximately 12,723 megawatts. The company was incorporated in 2019 and is headquartered in New York, New York.",
        "sector": {
            "industry": "Utilities",
            "sector_id": "ae008f52-f5e2-487d-aba8-065f2467101d"
        },
        "stock_price": {
            "stock_price": 1.56826,
            "peg_ratio": 0.0451896,
            "gross_profit_margin": 0.648055,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": null,
            "annual_stock_return": null,
            "de_ratio": 7.57049,
            "created_at": "2022-11-23T23:21:22",
            "average_volume": null,
            "current_ratio": 0.771689,
            "volume": null,
            "roe_ratio": 0.257977,
            "exchange_platform": null,
            "quick_ratio": 0.771689,
            "company": "BEPC",
            "price_risk": null,
            "pb_ratio": 1.56826,
            "stock_price_id": "BEPC-2021-12-31",
            "pe_ratio": 6.0791,
            "ps_ratio": 1.708
        }
    },
    {
        "company_id": "WMS",
        "name": "Advanced Drainage Systems, Inc.",
        "market_cap": 8006350000,
        "stock_price": 6.60412,
        "dividend_yield": 0.00535525,
        "profile_image": "https://financialmodelingprep.com/image-stock/WMS.png",
        "sector": "Industrials",
        "category": "Mid Market Cap",
        "ticker_symbol": "WMS",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 5.83637,
            "created_at": "2022-11-23T23:21:22",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Advanced Drainage Systems, Inc. designs, manufactures, and markets thermoplastic corrugated pipes and related water management products, and drainage solutions for use in the underground construction and infrastructure marketplace in the United States, Canada, Mexico, and internationally. The company operates through Pipe, International, Infiltrator, and Allied Products & Other segments. It offers single, double, and triple wall corrugated polypropylene and polyethylene pipes; plastic leachfield chambers and systems, EZflow synthetic aggregate bundles, mechanical aeration wastewater solutions, septic tanks and accessories, and combined treatment and dispersal systems; and allied products, including storm retention/detention and septic chambers, polyvinyl chloride drainage structures, fittings, and water quality filters and separators. The company also purchases and distributes construction fabrics and other geosynthetic products for soil stabilization, reinforcement, filtration, separation, erosion control, and sub-surface drainage, as well as drainage grates and other products. It offers its products for non-residential, residential, agriculture, and infrastructure applications through a network of approximately 38 distribution centers. The company was incorporated in 1966 and is headquartered in Hilliard, Ohio.",
        "sector": {
            "industry": "Industrials",
            "sector_id": "881b827b-e7bc-4819-8403-c18410a67cea"
        },
        "stock_price": {
            "stock_price": 6.60412,
            "peg_ratio": 1.11014,
            "gross_profit_margin": 0.289019,
            "date": "2022-03-31",
            "total_price_value": null,
            "dividend_yield": 0.00535525,
            "annual_stock_return": null,
            "de_ratio": 1.41922,
            "created_at": "2022-11-23T23:21:21",
            "average_volume": null,
            "current_ratio": 2.22854,
            "volume": null,
            "roe_ratio": 0.249288,
            "exchange_platform": null,
            "quick_ratio": 0.924949,
            "company": "WMS",
            "price_risk": null,
            "pb_ratio": 6.60412,
            "stock_price_id": "WMS-2022-03-31",
            "pe_ratio": 26.4919,
            "ps_ratio": 2.59562
        }
    },
    {
        "company_id": "WFC-PY",
        "name": "Wells Fargo & Company",
        "market_cap": 110385000000,
        "stock_price": 1.10856,
        "dividend_yield": 0.0174399,
        "profile_image": "https://financialmodelingprep.com/image-stock/WFC-PY.png",
        "sector": "Financial Services",
        "category": "High Market Cap",
        "ticker_symbol": "WFC-PY",
        "exchange_platform": "New York Stock Exchange",
        "current_ranking": {
            "score": 5.74233,
            "created_at": "2022-11-24T11:16:16",
            "updated_at": "2022-11-25T02:11:55"
        },
        "description": "Wells Fargo & Company, a diversified financial services company, provides banking, investment, mortgage, and consumer and commercial finance products and services in the United States and internationally. It operates through four segments: Consumer Banking and Lending; Commercial Banking; Corporate and Investment Banking; and Wealth and Investment Management. The Consumer Banking and Lending segment offers diversified financial products and services for consumers and small businesses. Its financial products and services include checking and savings accounts, and credit and debit cards, as well as home, auto, personal, and small business lending services. The Commercial Banking segment provides financial solutions to private, family owned, and certain public companies. Its products and services include banking and credit products across various industry sectors and municipalities, secured lending and lease products, and treasury management services. The Corporate and Investment Banking segment offers a suite of capital markets, banking, and financial products and services to corporate, commercial real estate, government, and institutional clients. Its products and services comprise corporate banking, investment banking, treasury management, commercial real estate lending and servicing, equity, and fixed income solutions, as well as sales, trading, and research capabilities services. The Wealth and Investment Management segment provides personalized wealth management, brokerage, financial planning, lending, private banking, and trust and fiduciary products and services to affluent, high-net worth, and ultra-high-net worth clients. It also operates through financial advisors. Wells Fargo & Company was founded in 1852 and is headquartered in San Francisco, California.",
        "sector": {
            "industry": "Financial Services",
            "sector_id": "3d900c0f-31ed-49c0-b036-3d4ad4a563e1"
        },
        "stock_price": {
            "stock_price": 1.10856,
            "peg_ratio": 0.0172349,
            "gross_profit_margin": 0.0,
            "date": "2021-12-31",
            "total_price_value": null,
            "dividend_yield": 0.0174399,
            "annual_stock_return": null,
            "de_ratio": 9.37048,
            "created_at": "2022-11-24T11:16:15",
            "average_volume": null,
            "current_ratio": 97.2547,
            "volume": null,
            "roe_ratio": 0.114858,
            "exchange_platform": null,
            "quick_ratio": 20.7358,
            "company": "WFC-PY",
            "price_risk": null,
            "pb_ratio": 1.10856,
            "stock_price_id": "WFC-PY-2021-12-31",
            "pe_ratio": 9.65156,
            "ps_ratio": 2.64959
        }
    }
]